## แบบฝึกหัด NumPy – การสร้างและใช้งานอาเรย์

In [ ]:
#ข้อ1.สร้างอาเรย์ 1 มิติ (1D array) สร้างอาเรย์ ขนาด 8 ที่มีค่าเป็น เลขคี่ จาก 1 ถึง 15 โดยใช้ np.arange()
import numpy as np
array_1d = np.arange(1, 16, 2)
print(array_1d)

[ 1  3  5  7  9 11 13 15]


In [ ]:
#ข้อ2.สร้างอาเรย์ 2 มิติ (2D array) สร้างอาเรย์ 3 แถว 5 คอลัมน์ ที่มีค่าเริ่มต้นทั้งหมดเป็น 9 โดยใช้ฟังก์ชันที่เหมาะสม (np.full() หรือวิธีอื่น)
array_2d = np.full((3, 5), 9)
print(array_2d)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [ ]:
#ข้อ3.สร้างอาเรย์ 3 มิติ (3D array) สร้างอาเรย์ 2 × 3 × 4 ที่มีค่าเป็น 0 ทั้งหมด โดยใช้ np.zeros() และตรวจสอบ shape ของอาเรย์นั้น
array_3d = np.zeros((2, 3, 4))
print(array_3d)
print("Shape:", array_3d.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Shape: (2, 3, 4)


In [ ]:
#ข้อ4.การใช้ np.linspace() สร้างอาเรย์ที่มี 10 ค่า ซึ่งกระจายจาก 0 ถึง 5 แบบมีช่วงเท่ากันทุกตำแหน่ง  ???
lin_array = np.linspace(0, 5, 10)
print(lin_array)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


## แบบฝึกหัด: NumPy Indexing & Slicing default_array = np.array([1,2,3,4,5,6]) default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12]

In [26]:
# ข้อ1.เลือกสมาชิกตัวสุดท้าย ของ default_array โดยใช้ index โดยสร้างตัวแปรชื่อ last_item เพื่อรับค่า
default_array = np.array([1, 2, 3, 4, 5, 6])
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12]
])
last_item = default_array[5]
print(last_item) 

6


In [13]:
# ข้อ2.เลือกสมาชิกตั้งแต่ตำแหน่งที่ 2 ถึง 4 (index 1–3) ของ default_array โดยสร้างตัวแปรชื่อ slice_2_to_4 เพื่อรับค่า
slice_2_to_4 = default_array[1:4]
print(slice_2_to_4)

[2 3 4]


In [27]:
# ข้อ3.เลือกค่าทั้งหมดในคอลัมน์ที่ 2 ของ default_array_2d โดยสร้างตัวแปรชื่อ column_2 hint [:, 1]
column_2 = default_array_2d[:, 1]
print(column_2)

[ 2  6 10]


In [28]:
# ข้อ4.เลือกค่าในแถวแรก 2 ตัวสุดท้าย ของ default_array_2d โดยสร้างตัวแปรชื่อ row1_last2 เพื่อรับค่า
row1_last2 = default_array_2d[0, 2:]
print(row1_last2)

[3 4]


In [29]:
# ข้อ5.เลือกค่าที่อยู่มุมขวาล่าง (แถวสุดท้าย คอลัมน์สุดท้าย) ของ default_array_2d โดยสร้างตัวแปรชื่อ bottom_right เพื่อรับค่า
bottom_right = default_array_2d[2, 3]
print(bottom_right)

12


## แบบฝึกหัด 3: คำนวณ (x^2 + 2x) เมื่อ x = [1,2,3,4]

In [31]:
x = np.array([1, 2, 3, 4])
result = ( x**2 + 2*x )
print(result)

[ 3  8 15 24]
