## 1. Import numpy as np เรียกใช้งาน numpy

In [1]:
import numpy as np

In [4]:
# syntax creating Array
# array_ = np.array()
# 1 - dimensiona1 array 1,5,2,0 
arr_1d = np.array([ 1, 5, 2, 0 ])
# 2 - dimensional array  1,5,2,0  8,3,6,1  1,7,2,9
arr_2d = np.array([ [1,5,2,0], [8,3,6,1], [1,7,2,9] ])

# 3 - dimensional array 10, 15, 20, 25   30, 35, 40, 45   50, 55, 60, 65 
arr_3d = np.array([ [10, 15], 
                [ 20, 25], 
                
                [30, 35], 
                [40, 45],
                
                [50, 55], 
                [60, 65] ])


In [3]:
print (arr_1d)

[1 5 2 0]


In [7]:
print(arr_1d)
print("           ")
print(arr_2d)
print("              ")
print(arr_3d)

[1 5 2 0]
           
[[1 5 2 0]
 [8 3 6 1]
 [1 7 2 9]]
              
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]]


In [8]:
default_array = np.array([1,2,3,4,5,6])
default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])

In [34]:
# สามตัวแรก จาก default_array
default_array[ :3]

# ตัวที่ 4 เป็นต้นไป default_array
# default_array[3:]

# สมาชิกใน row 2 columns 4 
# default_array_2d[1,3]

array([1, 2, 3])

In [12]:
array_attribute = np.array([ [  1, 2, 3, 4 ], [  5, 6, 7, 8 ], [ 9, 10, 11, 12 ] ])

In [ ]:
# ตรวจสอบคุณสมบัติของ Array
# array_attribute.ndim ดูว่ามีกี่มิติ 2
# array_attribute.shape ดูว่ามีแถวกี่คอลัมน์ (3ม 4)
# array_attribute.size จำนวนสมาชิก 12
# array_attribute.dtype ตรวจสอบข้อมูล

dtype('int64')

In [19]:
zero_2d_array = np.zeros(2)
one_1d_array = np.ones(5)
arange_array = np.arange(4)
step_arang_array= np.arange(2,9,2)  # start stop step 

In [ ]:
# zero_2d_array
print(zero_2d_array)
# one_1d_array
print(one_1d_array)
# arang_array
print(arange_array)
# step_arang_array
print(one_1d_array)

[0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3]
[1. 1. 1. 1. 1.]


In [20]:
data = np.array([ 1, 2])
ones = np.ones(2)# [1, 1 ]
b = np.array([ [1,1], [2,2] ])  
# [ 1, 1 ]  
# [ 2, 2 ]

In [21]:
sum = data + ones  
diff = data - ones 
multiply_array = data * ones 
divide_array = data/ones
col_sum = b.sum(axis=0) # ผลรวมแนว column
row_sum= b.sum(axis=1) # ผลรวมแนว row 

In [22]:
sum
diff
multiply_array
divide_array
# print(col_sum)  
print(row_sum)

[2 4]


In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a + b =", a + b)
print("a * 10 =", a * 10)
print("a ** 2 =", a ** 2)
print("b/2", b/2)

a + b = [5 7 9]
a * 10 = [10 20 30]
a ** 2 = [1 4 9]
b/2 [2.  2.5 3. ]


In [24]:
# a + b 
print("a + b =", a + b)
# a * 10 
print("a * 10 =", a * 10)
# a^2
print("a ** 2 =", a ** 2)
# b / 2 
print("b/2", b/2)

a + b = [5 7 9]
a * 10 = [10 20 30]
a ** 2 = [1 4 9]
b/2 [2.  2.5 3. ]


In [25]:
array_sample = np.arange(20)

In [26]:
print(array_sample)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
#reshape สองแถว
# array_sample.reshape(2,10)
#reshape 10แถว
# array_sample.reshape(10,2)
array_sample.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])